server:
  port: 8083
  
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://idp:9999/auth/realms/master
        registration:
          keycloak:
            client-id: master-realm
            client-secret: 09c0ca9b-d39c-4541-9499-6398c540ea3e
            authorization-grant-type: client_credentials
  kafka:
    bootstrap-servers: localhost:9092
    consumer.group-id: tenants

keycloakUri: http://idp:9999/auth